### ISSUE TITLE
CLI options?

### ISSUE THREAD

**Issue by ahopelesshadow** [ravesheep/ProtonVPN-windows#3]
I understand this should probably go to https://github.com/ProtonVPN/win-app  but I figured I actually use this fork, and I might have a better chance at getting a response here...  Ill copy the issue to there also just for the hell of it, but any chance on adding the ability to Open/connect to protonvpn via cli?  something like protonvpn.exe --connect --region USA --email user --password pass  or even to a specific server, i know you can just tap into openvpn, but I would prefer to use the proton exe.

**Comment by ravesheep** [comment]
I'm not sure how to do this right now, but I'll look into it.  
It's something I wish the official app had.

**Comment by ahopelesshadow** [comment]
> I'm not sure how to do this right now, but I'll look into it. It's something I wish the official app had.

Thanks friend, while im no coder, from having a quick look at things, the args would first need to determine if the app was logged in or not, since the state of the program seems to change based on that, but i also dont see where it calls a login check from my brief view of the source.  So it seems something like --login with username and pwd would need to be passed to the exe before anything else would work.

Also just an fyi, for anyone that attempts to use your fork with a free account (which is rather pointless since port forwarding isnt available) none of your options are even displayed, so an uneducated user may assume there is no difference, perhaps an update to the readme specifying that because port fwd requires proton paid accounts, this program will not show free users any additional settings.

**Comment by ravesheep** [comment]
I've now added basic command-line support.  
Commands don't output text/errors for now, so please check the [updated README](https://github.com/ravesheep/ProtonVPN-windows/blob/master/README.md) for more info.  

As long as you're logged into the app, commands will work.  
So instead of `protonvpn.exe --connect --region USA --email user --password pass`, the actual command would be:  
`protonvpn.exe --connect server us`.

Added in [v3.2.10.2](https://github.com/ravesheep/ProtonVPN-windows/releases/tag/3.2.10.2).
